### ISSUE TITLE
Incompatible with Detritus?

### ISSUE THREAD

**Issue by jaller94** [bagley/dokuwiki-securelogin#3]
The checkbox for the secured login does not show on the login page. This plugin broke on all my DokuWikis after the Detritus update. Login works just fine, however it's not encrypted. The key generation and test inside the admin area seems to be working fine.

Both Firefox and Chrome report a JavaScript error on line 75 of securelogin.js. The button seems to be undefined.

The version of my DokuWikis is 2015-08-10a "Detritus". I use clients running Ubuntu 12.04 and Windows 7.

**Comment by bagley** [comment]
I just pushed the fix. (Sorry, I was on vacation). Anyways, it should work, so let me know and if there's any other issues, please feel free to let me know.

**Comment by bagley** [comment]
And yes, they changed some of the javascript on the most recent version of dokuwiki. The updated version of the plugin reflects that.

**Comment by jaller94** [comment]
Thanks for taking the time and fixing the login.
This plugin is amazing.
