### ISSUE TITLE
2nd password is unencrypted when adding users

### ISSUE THREAD

**Issue by jaller94** [bagley/dokuwiki-securelogin#4]
While testing the plugin I noticed that the POST parameter "userpass2" is still unencrypted when adding a user.
Only the first password is blanked with ******, though the comparison works. DokuWiki detects correctly if the first and the second password match or not.

Tested on:
Chrome 45 and Firefox 41.0
with DokuWiki 2015-08-10a and Securelogin 2015-09-28

**Comment by bagley** [comment]
I fixed the issue. The javascript was not grabbing the second password and encrypting/sending/**** it properly. It's working now.

Sorry about the long delay. Life happened and I forgot about this issue.
