### ISSUE TITLE
Does this plugin add any value when using TLS?

### ISSUE THREAD

**Issue by jursed** [bagley/dokuwiki-securelogin#6]
I have an obvious question which I havn't seen answered anywhere.

If the entire DokuWiki website is served over TLS, does this plugin add any value? Given how HTTPS is proliferating (with the likes of Let's Encrypt), I'm just curious why this remains in active development. Is it for web hosting services which (still) don't/can't support HTTPS?

**Comment by bagley** [comment]
It's a good question. HTTPS is everywhere now, and that's a great thing. I think everyone should use it. It's made me previously wonder about the same question. Why have this plugin anymore if everything is encrypted?

Good security is like an onion, with multiple layers. It's never an "all or nothing" sort of thing. HTTPS does protect, but the encryption mechanisms it has used have had their share of vulnerabilities. BEAST affected SSL and TLS 1.0. SSL 3 had POODLE and several other attacks before getting yanked off the shelves. TLS 1.0 has been deprecated by numerous organizations (PCI/Mozilla/Google) as not being secure enough.

TLS 1.1, 1.2, and 1.3 all appear to be safe. But from what we've seen in the past, that will likely change in the future. When it does, there won't be a warning beforehand to upgrade. Instead, it will be suddenly, and it may take a while for people to upgrade to the next secure encryption method, all the while using the insecure one.

Besides the above, there are scenarios where TLS does not help. Some examples:

- A user logs into the site using a desktop or mobile browser that has a poor TLS implementation, bug, or vulnerability. The encrypted channel/data is then vulnerable to an attack.
- You or one of your users login from an organization, kiosk, or public computer that decrypts all TLS traffic. The password may be viewable to those that monitor the system. Trust should not be assumed here. Worse, if that user uses the same login in a social media site or a bank (which they shouldn't, but it happens), then the person monitoring and/or the organization can have access to those sites as well. Of course, we may say that the user shouldn't be logging in on these sorts of networks, but it can happen.
- A cross site vulnerability with your site may result in sending your password to an attacker. But if it's encrypted with the key that's only on the DokuWiki site, it will be useless to said attacker. (Note, you should be using cross site protection mechanisms as your main line of defense, not this plugin. They could still steal your login cookie, and get into the site that way.)

It's not guaranteed that securelogin will protect you in the above cases either. It's just another layer. A determined attacker may still be able to employ other methods to get the data. But as another layer, it makes it more difficult, and the attackers may move on to easier targets.

A counter argument is that Google and Facebook don't do this, so why should anyone else? Of course, they also have security experts to review their TLS settings, CORS (cross site) settings, and test for vulnerabilities.

So, do you need it? That depends. I've decided to leave that up to the individual site admins to decide.

But on that point, the admins should have the above points, to make an educated decision. I'll update the description with the above, to help them on that.

Let me know if I missed something, or if you have any other suggestions/ideas/concerns on this.

**Comment by jursed** [comment]
Thank you for the very thorough answer. I am impressed by how much thought you put into it.

The onion argument is a good one. The merits of it could be debated at length (my personal preference: a focus on robust and well set-up servers - both the HTTP proxy and application server - and restricting the TLS protocol to >=1.2), but you do make a good case for the usefulness of your plugin. I encourage you to put this information into the README.
